# this profile is activated by kubernetes dependencies
spring:
  cloud:
    kubernetes:
      enabled: true
      discovery:
        namespaces:
           - backend
        include-not-ready-addresses: true
eureka:
  client:
      enabled: false
OAUTH_AUDIENCES: oauth-client, b4dfe3fb-1692-44b8-92ab-366ccc84b539-authzmanager