logging:
  level:
    root: info
    me:
      sonam: info
info:
  app:
    name: Springboot me.sonam.account.Application
    description: This is a Springboot application
    version: 1.0.0

management:
  endpoint:
    health:
      show-details: always

server:
  port: 8080

spring:
  application:
    name: authentication-rest-service
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DBNAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    properties:
      sslMode: ${DB_SSLMODE}

eureka:
  client:
    serviceUrl:
      defaultZone: https://${EUREKA_USER}:${EUREKA_PASSWORD}@discovery-service.sonam.cloud/eureka

application-rest-service:
  root: ${APPLICATION_REST_SERVICE}
  client-role: /applications/clients/{clientId}/users/{userId}

jwt-service:
  root: ${JWT_REST_SERVICE}
  public-key-id: /jwts/publickeys/{keyId}
  accesstoken: /jwts/accesstoken

audience: ${JWT_USER_AUDIENCE}
scope: ${JWT_USER_SCOPE}
expiresInSeconds: ${JWT_USER_EXPIRES_IN_SECONDS}

permitpath:
  - path: /api/health/*
  - path: /authentications/authenticate
  - path: /authentications
    httpMethods: POST
  - path: /authentications/activate/*
    httpMethods: PUT

jwtrequest:
  - in:  /authentications/authenticate
    out: /applications/clients/(.)*/users/(.)*
    jwt: request

hmacKey:
  clientId: ${HMAC_CLIENTID}
  algorithm: ${HMAC_ALGORITHM}
  secretKey: ${HMAC_SECRET}