logging:
  level:
    root: info
    me:
      sonam: info
info:
  app:
    name: Springboot me.sonam.account.Application
    description: This is a Springboot application
    version: 1.0.0

management:
  endpoint:
    health:
      show-details: always

server:
  port: 8080

spring:
  application:
    name: authentication-rest-service
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DBNAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    properties:
      sslMode: ${DB_SSLMODE}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          audiences: ${OAUTH_AUDIENCES}

role-rest-service:
  root: ${ROLE_REST_SERVICE}
  user-role: /roles/clientId/{clientId}/users/{userId}

auth-server:
  root: http://authorization-server/issuer
  oauth2token:
    path: /oauth2/token
    params: ?grant_type=client_credentials

permitpath:
  - path: /authentications/api/health/*
  - path: /authentications/authenticate
  - path: /authentications
    httpMethods: POST
  - path: /authentications/activate/*
    httpMethods: PUT
  - path: /authentications/noauth/password
    httpMethods: PUT

jwtrequest:
  - in:  /authentications/authenticate
    out: /roles/clientId/(.)*/users/(.)*
    accessToken:
      option: request
      scopes: ${REQUEST_SCOPES}
      base64EncodedClientIdSecret: ${BASE64_CLIENT_ID_SECRET}