logging:
  level:
    root: info
    me:
      sonam: info
info:
  app:
    name: Springboot me.sonam.account.Application
    description: This is a Springboot application
    version: 1.0.0

management:
  endpoint:
    health:
      show-details: always

server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DBNAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    properties:
      sslMode: ${DB_SSLMODE}

eureka:
  client:
    serviceUrl:
      defaultZone: https://${EUREKA_USER}:${EUREKA_PASSWORD}@discovery-service.sonam.cloud/eureka

application-rest-service:
  root: ${APPLICATION_REST_SERVICE}
  client-role: /clients/{clientId}/users/{userId}

#jwt-rest-service: http://jwt-rest-service-mychart.backend.svc.cluster.local:80/jwts/accesstoken
audience: sonam.cloud
expireField: 10 # Hours Per Calendar Api
expireIn: 24 # expire in 24 hours

jwt-rest-service-public-key-id: ${jwt-rest-service-public-key-id}
jwt-rest-service-accesstoken: ${jwt-rest-service-accesstoken}


me.sonam.jwt-validator:
  permitpath:
    - path: /api/health/*
    - path: /authentications/authenticate
    - path: /authentications
      httpMethods: POST
    - path: /authentications/activate/*
      httpMethods: PUT