logging:
  level:
    root: error
    me:
      sonam: info
info:
  app:
    name: Springboot me.sonam.account.Application
    description: This is a Springboot application
    version: 1.0.0

management:
  endpoint:
    health:
      show-details: always

server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DBNAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    properties:
      sslMode: REQUIRE

application-rest-service:
  root: http://application-rest-service-mychart.backend.svc.cluster.local:80/applications
  client-role: /clients/{clientId}/users/{userId}

jwt-rest-service: http://jwt-rest-service-mychart.backend.svc.cluster.local:80/create/{username}/{audience}/{expireField}/{expireIn}
audience: sonam.cloud
expireField: 10 # Hours Per Calendar Api
expireIn: 24 # expire in 24 hours

permitPaths: /api/health/*
jwt-rest-service-public-key-id: http://localhost:{port}/jwt-rest-service/publickeys/{keyId}